version: "3.8"
services:
  cassandra:
    image: cassandra:4
    container_name: cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=TrafficCluster
      - CASSANDRA_NUM_TOKENS=16
    ports: ["9042:9042"]
    volumes:
      - cassandra_data:/var/lib/cassandra

  redis:
    image: redis:7
    container_name: redis
    ports: ["6379:6379"]

  scraper:
    build: ./scraper
    depends_on: [cassandra]

  traffic-generator:
    build: ./traffic-generator
    depends_on: [cassandra]

  cache-service:
    build: ./cache
    depends_on: [redis]

volumes:
  cassandra_data: