services:
  cassandra:
    image: cassandra:4
    container_name: cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=TrafficCluster
      - CASSANDRA_NUM_TOKENS=16
    ports: ["9042:9042"]
    volumes:
      - cassandra_data:/var/lib/cassandra

  redis:
    image: redis:7
    container_name: redis
    ports: ["6379:6379"]
    command: redis-server --maxmemory 5mb --maxmemory-policy allkeys-lru

  scraper:
    build: ./scraper
    depends_on: 
      - cassandra
      - storage
    volumes:
      - ./scraper/data:/app/data

  storage:
    build:
      context: ./storage
    image: proyecto_storage
    container_name: storage
    depends_on:
      - cassandra
    ports:
      - "5000:5000"

  traffic-generator:
    build: ./traffic-generator
    depends_on: [cassandra]

  cache-service:
    build: ./cache
    depends_on: [redis]
    ports:
      - "8080:5000"

volumes:
  cassandra_data: